name: CI BE
on: push

jobs:
  test:
    name: Link, Type check, Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Prune
        run: npx turbo prune --scope=backend

      - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@v3
        with:
          path: out/node_modules/.cache/turbo # workaround see: https://github.com/vercel/turborepo/issues/451
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-${{ github.ref_name }}-

      # Throw an error if the yarn.lock file doesn't match the installed dependencies (rather than updating it in-place, which it does by default locally)
      - name: Install
        working-directory: ./out
        run: yarn install --frozen-lockfile --silent

      - name: Lint
        working-directory: ./out
        run: yarn lint:backend

      - name: Type-check
        working-directory: ./out
        run: yarn type-check:backend

      - name: Build
        working-directory: ./out
        run: yarn build:backend
